- name: 'Namespace: Authentication'
  description: Issues and PRs related to user authentication.
  color: E3B724
- name: 'Namespace: OAuth'
  description: Issues and PRs related to our OAuth spec implementation.
  color: E3B724
- name: 'Namespace: Project'
  description: Issues and PRs related to the project in general.
  color: E3B724
- name: 'Namespace: Miscellaneous'
  description: Issues and PRs that don't belong in any other namespace
  color: E3B724
- name: 'Bug Status: Unverified'
  description: Issues that report unverified bugs. Pending for inspection.
  color: f9d0c4
- name: 'Bug Status: Confirmed'
  description: Issues that report confirmed bugs.
  color: f9d0c4
- name: 'Bug Status: Already Fixed'
  description: Issues that report already fixed bugs.
  color: B3E88C
- name: 'Bug Status: Fixed'
  description: Issues that report bugs and have been fixed.
  color: 22DC2C
- name: 'Bug Status: Waiting for author'
  description: Issues that report bugs and are pending of a response from the author.
  color: 2A5E9B
- name: 'Bug Status: Cannot Reproduce'
  description: Issues that report bugs that cannot be reproduced.
  color: 2A5E9B
- name: 'Bug Status: Fixed in master'
  description: Issues that report bugs from stable, but that are fixed in master.
  color: 2A5E9B
- name: 'Meta: Feature'
  description: Issues and PRs related to new features.
  color: BCBCBC
- name: 'Meta: Refactor'
  description: Issues and PRs related to refactors.
  color: BCBCBC
- name: 'Meta: Error Handling'
  description: Issues and PRs related to error handling.
  color: BCBCBC
- name: 'Meta: Cleanup'
  description: Issues and PRs related to code cleanup.
  color: BCBCBC
- name: 'Meta: Dependencies'
  description: Issues and PRs related to dependencies.
  color: BCBCBC
- name: 'Meta: VCS'
  description: Issues and PRs related to GitHub.
  color: 000000
- name: 'Meta: BugFix'
  description: PRs that fix bugs or issues.
  color: BCBCBC
- name: 'Meta: Question'
  description: Issues that do not belong to the Issue Tracker and should be asked in the official Discord Server.
  color: BCBCBC
- name: 'Meta: Security'
  description: Pull requests that address a security vulnerability
  color: BCBCBC
- name: 'Meta: Maintenance'
  description: Issues and PRs related to the maintenance of a certain piece of code.
  color: BCBCBC
- name: 'Meta: Proposal'
  description: Issues that request a new feature or a change in the api's interface.
  color: BCBCBC
- name: 'Meta: RFC'
  description: Issues that represent open Request for Comments
  color: B8E112
- name: 'Meta: Resolved RFC'
  description: Issues that represent closed/resolved Request for Comments
  color: B8E112
- name: 'Meta: Performance'
  description: Issues and PRs related to the performance of the api's interface.
  color: BCBCBC
- name: 'Meta: Enhancement'
  description: Issues and PRs related to feature enhancement.
  color: BCBCBC
- name: 'Meta: Consistency'
  description: Issues and PRs related to code consistency.
  color: BCBCBC
- name: 'Status: WIP'
  description: Issues and PRs that are still a work in progress.
  color: D3ECD8
- name: 'Status: Needs Testing'
  description: PRs that need testing from the author or volunteers.
  color: D3ECD8
- name: 'Status: Stalled'
  description: Issues and PRs that are being set aside for now for rethinking
  color: D3ECD8
- name: 'Status: Ready To Merge'
  description: PRs that are ready to merge.
  color: 22DC2C
- name: 'Status: Review Ready'
  description: PRs that are ready for author review.
  color: 20DA2A
- name: 'Status: Needs Docs'
  description: PRs that need documentation
  color: D3ECD8
- name: 'Status: Help Wanted'
  description: Issues that need assistance from volunteers or PRs that need help to proceed.
  color: D3ECD8
- name: 'Status: Invalid'
  description: Issues that will not be fixed or PRs that will not merge, e.g. due to backwards compatibility.
  color: 9C0404
- name: 'Status: Duplicate'
  description: Issues/PRs that are duplicated.
  color: 9C0404
- name: 'Status: Denied'
  description: Issues or PRs that have been denied by the team.
  color: 9C0404
- name: 'Status: Changes Requested'
  description: PRs that have requested changes.
  color: 9C0404
- name: 'Status: Blocked'
  description: PRs that are blocked by other issues/PRs.
  color: D3ECD8
- name: 'SEM: Patch'
  description: PRs that contain bugfixes and should be released in the next patch version.
  color: B1BE1E
- name: 'SEM: N/A'
  description: PRs that only contain documentation changes and do not change the api's interface.
  color: B1BE1E
- name: 'SEM: Major'
  description: PRs that contain breaking changes and should be released in the next major version.
  color: B1BE1E
- name: 'SEM: Minor'
  description: PRs that contain new features and should be released in the next minor version.
  color: B1BE1E
- name: 'Priority: Low'
  description: Issues that must be fixed or PRs that must be finished and merged with low priority.
  color: 22DC2C
- name: 'Priority: Medium'
  description: Issues that must be fixed or PRs that must be finished and merged with medium priority.
  color: F5F519
- name: 'Priority: High'
  description: Issues that must be fixed or PRs that must be finished and merged with high priority.
  color: F47C04
- name: 'Priority: Critical'
  description: Issues that must be fixed or PRs that must be finished and merged with maximum priority.
  color: 9C0404
