name: Unit Tests

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  test:
    name: ${{ matrix.os }}-rust-${{ matrix.rust }}
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.continue-on-error }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        rust: [beta, nightly]
        continue-on-error: [false]
        include:
          - os: ubuntu-latest
          - rust: stable
          - continue-on-error: true

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        name: Install toolchain
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true
      - name: Cache build artifacts
        id: cache-build
        uses: actions/cache@v2
        with:
          path: target/**
          key: ${{ runner.os }}-build-cache-${{ matrix.rust }}
      - uses: actions-rs/cargo@v1
        with:
          command: build
      - uses: actions-rs/cargo@v1
        with:
          command: test
